#!/bin/bash
# Quick reference card

echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║           RASPBERRY PI QUICK REFERENCE CARD              ║"
echo "╠══════════════════════════════════════════════════════════╣"
echo "║ COMMAND          │ DESCRIPTION                           ║"
echo "╠══════════════════════════════════════════════════════════╣"
echo "║ help             │ Full help menu                        ║"
echo "║ quickref         │ This quick reference                  ║"
echo "║ status           │ System status                         ║"
echo "║ wifiman          │ Wi-Fi Manager (menu)                  ║"
echo "║ apsetup          │ Access Point setup                    ║"
echo "║ apoff            │ Turn off AP mode                      ║"
echo "║ wifi on          │ Turn Wi-Fi on                         ║"
echo "║ wifi off         │ Turn Wi-Fi off                        ║"
echo "║ wifi scan        │ Scan for networks                     ║"
echo "║ wifi status      │ Show connection status                ║"
echo "║ wifi connect     │ Connect to network                    ║"
echo "║ wifi disconnect  │ Disconnect from network               ║"
echo "║ wifi list        │ List saved networks                   ║"
echo "║ myip             │ Show IP address                       ║"
echo "║ reboot           │ Reboot the Pi                         ║"
echo "║ shutdown         │ Shutdown the Pi                       ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
